name: stage-1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: jupyter/scipy-notebook:4b830d5897d8

    steps:
    - uses: actions/checkout@v3
    - name: Build stage-1 Docker image
      run: docker build --file raku-Dockerfiles/stage-1/Dockerfile --tag p6steve/rakudo:scipynb-2022.02-arm64-$(date +%s) --platform linux/amd64
