name: rakudo:scipy -> DH

on:
  push:
    paths:
      - scipy/Dockerfile
      - .github/workflows/scipy-weekly.yaml
  schedule:
      - cron: "23 1 * * 5"

jobs:
  build-scipy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: scipy
          file: ./scipy/Dockerfile
          tags: librasteve/rakudo:scipy
          push: true
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

